name: tests
on: [push, pull_request]
permissions:
  contents: read
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with: { ref: ci, path: _ci }
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: python -m unittest discover -s _ci/tests -v
        env:
          PLUGIN_ROOT: ${{ github.workspace }}
